### ISSUE TITLE
De-couple knowledge base from static page

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#1]
Discussed before @CMR248, @Freymaurer. 

As we are hoping for contributions from multiple people, it would be (a) safer and (b) easier to understand for newbies to de-couple the knowledge base from the main dataplant hp and make it an independent gh repository.

**Comment by Freymaurer** [comment]
This repo should now work as intended!

**Comment by Brilator** [comment]
Only the old content (https://nfdi4plants.org/content/docs/*) needs to be removed and the permanent link (is still https://nfdi4plants.org/content/docs/ResearchDataManagement.html) to the knowledge base needs to be changed in navbar and footer

**Comment by Freymaurer** [comment]
Thats right! I need to update some of the other docs repos first, then i'll start changing stuff in the web-components, the switch should then happen today ~23:00.
During this split only the urls will be changed and tomorrow i will delete the old docs from the nfdi4plants.github.io.
