### ISSUE TITLE
Swate Desktop installation: Specify for alternatives?

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/nfdi4plants.knowledgebase#101]
Some users with older Excel versions (2019, 2021, ...) are confused about the installation process (when the normal installer.cmd does not work). Often the alternatives that are noted below work but users don't realize that they may be applicable. Perhaps we should specify this?:

> 💡 As a university trying to publish to the Excel add-in store we encountered some legal roadblocks. Hence the current installer is far from perfect. Please check out the alternatives, if the installer does not work for your setup.

to

> 💡 As a university trying to publish to the Excel add-in store we encountered some legal roadblocks. Hence the current installer is far from perfect. Please check out the _Alternatives_ (noted below), if the installer does not work for your setup. This especially applies to standalone MS Excel versions (e.g. ***Excel 2019***, ***Excel 2021***, etc.), too.
> Please note that we cannot guarantee compatibility of Swate with Excel versions that are *not* part of MS 365.

**Comment by Brilator** [comment]
Good idea. 

My suggestion: 

- [ ] open a PR
- [ ] add a note to sidebar "Desktop (via installer)" that this is in **beta**
- [ ] add a note **recommended** to the sidebar of "Desktop (manually)" 
- [ ] add a more step-by-step instructions for Windows on how to side load the app (similar to the macOS docs)

**Comment by omaus** [comment]
> add a more step-by-step instructions for Windows on how to side load the app (similar to the macOS docs)

This is not needed since Microsoft provides a step-by-step guide on their official docs. See [here](http://127.0.0.1:8080/docs/implementation/SwateManual/swate_installation_manual.html) and [here](https://learn.microsoft.com/de-de/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins).

**Comment by Brilator** [comment]
1. First link is dead
2. MS guides are overwhelming for someone who just quickly wants (and than is too frustrated) to use Swate

**Comment by Brilator** [comment]
I guess my main point was: suggesting a change via PR takes almost no more time than opening this issue

**Comment by Brilator** [comment]
Ok, I just saw _how_ annoying the instructions are for Windows... So I see, why you wouldn't want to re-do it. But as a standard user wanting to test swate for the first time, I would be too lazy to follow it.

**Comment by omaus** [comment]
> I guess my main point was: suggesting a change via PR takes almost no more time than opening this issue

It's in the doing and already halfway done.

> Ok, I just saw how annoying the instructions are for Windows... So I see, why you wouldn't want to re-do it. But as a standard user wanting to test swate for the first time, I would be too lazy to follow it.

I looked through the docs and don't know how to do it better. They even provide pictures for the some a bit more difficult steps. Yes, it's much but if we shorten it, it's possible that it becomes too abbreviated to be understandable.

**Comment by omaus** [comment]
> First link is dead

Omfg, that was the local link. 😂
Try this instead: https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/SwateManual/swate_installation_manual.html
