### ISSUE TITLE
ARC-specification

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants.knowledgebase#114]
The knowledge base should include information about the ARC-specification, either replacing the related repository (https://github.com/nfdi4plants/ARC-specification), or directly referencing it. 

Related to this, the Swate manual currently contains most of the Annotation Table specs. This information should be extracted and moved to the specs docs, and only get linked from the Swate docs.

**Comment by Martin-Kuhl** [comment]
The ARC-specification is already linked in [this](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/AnnotatedResearchContext.html#framework) and [this part](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/QuickStart_arc.html#violas-arc).
Did you think of something like this or do you envision something else?
