### ISSUE TITLE
Video file cannot be played

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/nfdi4plants.knowledgebase#119]
Attempted to embed the ArcInit.mov file into the ARC Commander QuickStart.
File was detected as video but could not be played 

`<video controls><source src="ArcInit.mov" type="video/mp4"></video>`

**Comment by Brilator** [comment]
I'd suggest to upload videos to the dataplant YouTube channel and embed from there. Otherwise this repo here will become very big.

**Comment by Freymaurer** [comment]
This sounds like a very good solution. Can you go ahead and give it a try, to see if this approach works?

**Comment by Brilator** [comment]
Tried this with the swate videos some time ago. 
https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/b6aabcdb73f9443ca1603e61c3e240c68114d3d7/src/docs/swate_videos.md

**Comment by Martin-Kuhl** [comment]
Just tested it with the Swate videos again, and it seems to work without problems. Will upload a first video to YT and give it a try, thanks!

**Comment by Freymaurer** [comment]
So we can close this?

**Comment by Martin-Kuhl** [comment]
For the moment, yes. I'll reopen if I encounter trouble again.
