### ISSUE TITLE
Bug with code blocks in ontology article 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#132]
The code blocks (schema examples) are not displaying correctly in the [ontologies](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/fundamentals/Ontologies.html) article: 

<img width="924" alt="Screenshot 2023-05-15 at 22 27 26" src="https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/16229676/630db269-fd28-46f5-b808-a10471d7a1ae">

Probably linked to the recent implementation of mermaid graphs; see bottom of the site: 

<img width="1440" alt="Screenshot 2023-05-15 at 22 27 38" src="https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/16229676/92698a09-8b8b-4617-9187-008ac94b248a">
 
I assume it would help to define the code blocks as e.g. "```markdown" or "```bash"

**Comment by Freymaurer** [comment]
Update to web-components version 1.0.0, this should fix the issue

**Comment by Brilator** [comment]
Hm, that didn't solve it. Or I didn't understand it.

**Comment by Freymaurer** [comment]
After updating web-components you need to use rollup to bundle the js to make it usable in html.

**Comment by Brilator** [comment]
Ok, I don't know what that means. Sorry.

**Comment by Freymaurer** [comment]
I am currently working on the searchbar and the new sidebar, can do this afterwards 👍
