### ISSUE TITLE
[topic] Reproducibility / CWL 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#194]
We need to bring the reproducibility topic into the knowledge base

There are two drafts / note collections in the `reproducibility` branch. 

- [ ]  Reproducibility in general...

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/reproducibility/src/docs/fundamentals/ReproduceReuse.md

- [ ]  CWL

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/reproducibility/src/docs/fundamentals/CommonWorkflowLanguage.md

**Comment by Brilator** [comment]
@eik-dahms, would you be interested in contributing a short article / paragraph on reproducibility?

**Comment by eik-dahms** [comment]
Sure - I will look into it!

**Comment by Brilator** [comment]
Sorry, this was mostly a list of thoughts and notes. 
Rough idea was two articles:
1. one on an abstract level (fundamentals) about reproducibility in general
2. one on a concrete level (implementation) about CWL and how the ARC fosters reproducibility

**Comment by Brilator** [comment]
#355
