### ISSUE TITLE
Discuss conventions for naming and content (here Quickstart) 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#20]
The three "QuickStart"s are currently 

1. QuickStart on ARCs
2. ARC Commander QuickStart
3. Swate QuickStart

I would suggest to stick to the same naming convention (in titles and articles), e.g. 
1. QuickStart on ARCs or ARC QuickStart
2. QuickStart ARC Commander  or ARC Commander QuickStart
3. QuickStart Swate or Swate Quickstart 

And to me "Quick Start" implements that the user can follow this to get _quickly started_. So I would reserve the term for "hands-on" tutorials. 
The "QuickStart on ARCs" is more a user story / use-case / user scenario.

**Comment by Brilator** [comment]
@andreaschrader @Martin-Kuhl @CMR248

**Comment by andreaschrader** [comment]
Added the Hackathon label as it is an aftermath of this and it reminds us of the discussion there related to the reordering of the sidebar also after a break.
Both points agreed on from my side. 
I suggested the "QucikStart on ARC" ... version as this improves to find the Quickstarts in the sidebar on one glance.
We could eventually have one QuickStart for all, also for DataHUB and DataPLAN if possible. Is this feasible to add this to the knowledgebase?

**Comment by Brilator** [comment]
> We could eventually have one QuickStart for all, also for DataHUB and DataPLAN if possible. Is this feasible to add this to the knowledgebase?

Yes and yes! We should get started to (draft) write those contents and invite the respective people to contribute.

**Comment by Brilator** [comment]
> Added the Hackathon label as it is an aftermath of this and it reminds us of the discussion 

I was honestly going to ask, if we still need the hackathon label as it looks like we didn’t finish up on those tasks and it’s not really saying anything. :) 
Next time we could formulate a Hackathon Milestone.

**Comment by CMR248** [comment]
I guess this issue is finished, or @Brilator

**Comment by Brilator** [comment]
IMO the different uses of „quickstart“ is not solved. 
The Quickstarts to ARC Commander and Swate are conceptionally different
1. ARC C: Follow these exact steps to come to a clear goal.
2. Swate: These are things you can do, try out yourself.

**Comment by CMR248** [comment]
Okee. I understand. Do we need to discuss this point collectively in the JF?

**Comment by Martin-Kuhl** [comment]
@Brilator Yes, but I doubt that it is useful to supply a similar quickstart for Swate as for the ARC Commander, as the first steps for the AC are almost always identical. In Swate it makes more sense to give a quick overview on the options you have in Swate. Maybe we just need to rename the quickstart for Swate? 
Or maybe rename it and provide additionally a minimal example for Swate.

**Comment by Brilator** [comment]
> Or maybe rename it and provide additionally a minimal example for Swate.

I'd suggest to do that. With a few example terms and tasks, that definitely work well. Instrument model -> pick from list. Temperature, add unit. File picker -> add your files, etc.
