### ISSUE TITLE
[Enhancement] Use yaml only with indentation

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#207]
In the teaching materials section, a yaml header is used.
The part for authors looks as below nicely grouping name, orcid and github.

author: 
- name: XYZ
  orcid: xyz-orcid
  github: xyz-github

Suggestion: Remove the dash. I only know and see yaml headers only with indentation - without the dash.

author: 
  name: XYZ
  orcid: xyz-orcid
  github: xyz-github

**Comment by Brilator** [comment]
```yaml
author:
name: XYZ
orcid: xyz-orcid
github: xyz-github
```

This would not allow to properly add multiple authors

**Comment by Brilator** [comment]
https://www.w3schools.io/file/yaml-array-objects/

**Comment by Brilator** [comment]
The alternative is json syntax as [originally](https://nfdi4plants.github.io/web-components-docs/docs/SupportedStaticSiteGenerators.html#fornax) intended for the knowledge base. 

```yaml
author: {name: Martin D'vloper, github: https://github.com/exampleUrl, orcid: 0000-0000-0000-0000}
```

**Comment by andreaschrader** [comment]
Or like this:

author:
- [name, github, orcid]: [Martin D'vloper, https://github.com/exampleUrl, 0000-0000-0000-0000]

Would be maybe a good idea to specify the YAML version used. 
Thanks, it is solved for now.
