### ISSUE TITLE
PDF-Export

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/nfdi4plants.knowledgebase#23]
Feature Request:
An export of the Knowledgebase-Content as PDF would be desirable.

**Comment by Brilator** [comment]
This is probably not what you meant, but I've fiddled around with a pandoc solution. 
Would however require to run this locally (plus dependencies pandoc and latex). 

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/tree/main/src/docs/_ignored/pandoc_tests

**Comment by Brilator** [comment]
I've also made an example pdf with a "DataPLANT-themed" title page. 

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/main/src/docs/_ignored/pandoc_tests/DataPlantOnboarding.pdf

**Comment by CMR248** [comment]
This was just a suggestion from @andreaschrader , which she made during the ARC Hackathon. I think it would be great to have the possibility to export single articles or the complete KB as PDF on the rendered page (without dependencies).
This surely isn't the highest priority, but maybe @Freymaurer has an idea how this could be solved in a technically simple way.

**Comment by Freymaurer** [comment]
Something like [this](https://md2pdf.netlify.app)? How should this be implemented?

**Comment by CMR248** [comment]
Something like that could be imaginable. Perhaps one could simply integrate a button directly on the KB landing page, which allows the download of the KB as a PDF. 
Do you think it's possible to create an automated procedure that always generates a new PDF as soon as something has been changed in the KB? This way one wouldn't have to think about it every time one changes something.

**Comment by Freymaurer** [comment]
> Do you think it's possible to create an automated procedure that always generates a new PDF as soon as something has been changed in the KB? This way one wouldn't have to think about it every time one changes something. 

Would the result of this be good enough?

![image](https://user-images.githubusercontent.com/39732517/196722356-52154154-1631-42d2-9822-f75497a9bfe4.png)

**Comment by andreaschrader** [comment]
I had something like "Read the docs" in mind when intending to read  through the material knowing to be probably cut off from stable internet for a while.
