### ISSUE TITLE
[guide] How to Helpdesk Tutorial

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#235]
**Guide needed**
*Please name and describe the guide you'd like to see with a few bullet points*
- Helpdesk Tutorial
- This is the previous teaching-materials repo issue #339 of @CMR248. 

:bulb: If you want to contribute a tutorial, please refer to the [contribution guide](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/CONTRIBUTING.html).

**Comment by Brilator** [comment]
Can one of you pleas add to this? @CMR248 @andreaschrader 

1. Where would you put this guide? (Guides -> Contributions, FAQ, a new section under guides)
2. What should this guide contain? Screen shots of the Helpdesk? Or is it enough to just add the link somewhere and explain what it is good for?

**Comment by andreaschrader** [comment]
@CMR248 ?

**Comment by CMR248** [comment]
Since the Helpdesk is self-explanatory, a tutorial is not necessary.
