### ISSUE TITLE
[guide] Ontology contribution

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#240]
**Guide needed**
*Please name and describe the guide you'd like to see with a few bullet points*
How to contribute to the DataPLANT ontology

This is an issue brought up by others in today's Data Steward cycle.
As far as I understood, it was suggested to add a brief description how to contribute and link to the README of the respective tutorial which is already describing this.

Please assign yourself or specifiy if this does not cover all points discussed in this respect.

**Comment by AngelaKranz** [comment]
@StellaEggels

**Comment by StellaEggels** [comment]
We added a knowledge base article that includes a section on how to contribute to the DataPLANT ontology: https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/OntologyServiceLandscape.html#your-contribution--missing-ontologies-and-terms
