### ISSUE TITLE
[bug] search functionality could be optimized

### ISSUE THREAD

**Issue by wunderbarr** [nfdi4plants/nfdi4plants.knowledgebase#248]
When I try to find this page: https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/ArcCommanderManual/arc_config.html
I enter `arg config` in the search bar, but the relevant page is not there.
So I think the search functionality should be optimized. Otherwise it is hard to use.

**Comment by Brilator** [comment]
Thanks for pointing this out @Freymaurer

**Comment by Freymaurer** [comment]
It is the first hit for me?

**Comment by wunderbarr** [comment]
But for me, it works like this:

![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/23312330/a8638b38-f02d-4d72-b14c-a19074b19a55)

**Comment by Freymaurer** [comment]
Ahh! You mean if you search for "ar**g** config"? With a `g` instead of `c`? 

I am sorry for the inconvienience, but it is very difficult to catch typos for short acronyms like `arc`.

**Comment by wunderbarr** [comment]
Thank you. I have not realized there is a typo. I think I can close the issue. Sorry for that.
