### ISSUE TITLE
[bug] Swate Browser Installation

### ISSUE THREAD

**Issue by wunderbarr** [nfdi4plants/nfdi4plants.knowledgebase#257]
In the fourth step, the guidance is as the following: 
`Open a (new) workbook, click Insert → Office Add-ins/Add-ins → Upload My Add-in`.
However, there is no Add-ins button in the Insert tab.
![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/23312330/2c0d217f-4c04-46bc-bcbd-8acf25bcea8c)
Currently, the Add-ins button is in the Home tab. And the remaining steps should also be updated.
![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/23312330/c302e81e-bfa1-4424-bd58-73ff5dc4878d)

**Comment by wunderbarr** [comment]
Documentation link: https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/SwateManual/swate_installation_browser.html

**Comment by Brilator** [comment]
Thanks, good catch. I've updated and added a screen shot. 
Can you explain, what else needs updates in the later steps ?

**Comment by wunderbarr** [comment]
By default, it will navigate to the store:
![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/23312330/d1bb93c9-70e3-4b87-a6a0-7828313b7fc1)
So we need to click the `MY ADD-INS`, and find the `Upload My Add-in` in the right corner.
![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/23312330/d16f0818-3d93-4867-b1cc-571256685153)

**Comment by Brilator** [comment]
Huh, interesting. This is not the case in my browser (safari, macOS). 
Can you kindly provide a comment on this via PR?

**Comment by wunderbarr** [comment]
I use Chrome in Ubuntu 22.04. I just check all open PRs (pull request), but I don't find any related PR. So I comment here.

**Comment by Brilator** [comment]
Sorry, I meant to open a PR yourself and add such a comment pointing future users that they might have to with the add-ins tab

**Comment by Brilator** [comment]
done :)
