### ISSUE TITLE
discuss indexing knowledge base as OER

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#258]
Follow up on discussion over teaching poster at cordi 

https://oersi.org/resources/

@andreaschrader 
@muehlhaus

**Comment by andreaschrader** [comment]
How to add an OER to OERSI in case this should be done:
https://oersi.org/resources/pages/en/faq/#how-can-i-add-my-oer-to-oersi

**Comment by Brilator** [comment]
Closed for now due to knowledge base re-launch. Will discuss again on higher level in combination with training materials.
