### ISSUE TITLE
Add clear licenses for all images in the knowledgbase

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#259]
Another follow up on poster discussions (teaching material poster) at CoRDI, see also the required indexing in #258:

Please add a clear licenses and authors for images available for reuse in the knowledgbase in the sense of an OER especially before and if adding it to https://oersi.org/resources/pages/en/

**Comment by Brilator** [comment]
This is the current state: https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/img/_ImageIndex.html

Of course not enough, put could develop from there.

**Comment by Brilator** [comment]
I have now updated this to at least display all images presently in the knowledge base img folder. #260 

However, as stated in the PR, this requires a major overhaul and double-check. Many sources are blank. And for many, I've just gone over it by "fill-down" in Excel...

**Comment by Brilator** [comment]
Thanks @andreaschrader for the push though. 
We really need to take proper care of image credits, etc. 

@CMR248

**Comment by Brilator** [comment]
This only displays in the .de, not the .org site and I do not know why :( @Freymaurer ? 

- https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/img/_ImageIndex.html
- https://www.nfdi4plants.org/nfdi4plants.knowledgebase/docs/img/_ImageIndex.html

**Comment by Freymaurer** [comment]
I can have a look, please ping me again if i forget this.

**Comment by Freymaurer** [comment]
So let me be honest, this is the hosting information i have from gh-pages:

![image](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/assets/39732517/c5a4ea95-7ea4-4c2c-b5e3-9c0657713b9c)

I do not know where these .de/.org forwards originate from...

.. but i do remember that github dislikes urls with "_" in them, so a simple file name change could resolve this issue. Give it a try please

**Comment by Brilator** [comment]
> but i do remember that github dislikes urls with "_" in them,

WOW! That explains a lot of issues with logos (stored in img/_logos) not displaying properly!!!

**Comment by Brilator** [comment]
Still interesting, that this is not an issue on .de. 
Anyways, the index has now moved to 
https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/image-index.html

**Comment by Freymaurer** [comment]
> Still interesting, that this is not an issue on .de.

Maybe they shadow this repo and host it on their own, whereas the .org is just a redirect to the .io page

**Comment by Brilator** [comment]
Closed for now due to knowledge base re-launch. Will discuss again on higher level in combination with training materials.
