### ISSUE TITLE
[bug] Swate Dev Docs missing

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#288]
Not sure / cannot remember, if there was a misunderstanding at some point.

The KB currently do not contain the Swate Dev docs, but only user-targeted docs. 

- [ ] [Swate Manual](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/SwateManual/index.html) contains dead link
- [ ] This part is not in KB and I don't know, if it should https://github.com/nfdi4plants/Swate-docs/tree/main/src/docs/DevDocs

**Comment by Freymaurer** [comment]
Swate-docs was its own repo, which i archived a few weeks ago, as it was no longer maintained or needed after our decision to collect all information in the knowledgebase

https://github.com/nfdi4plants/Swate-docs

All content is still available in the repo, just the website is no longer published
