### ISSUE TITLE
define describe protocol usage

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/nfdi4plants.knowledgebase#30]
**Is your feature request related to a problem? Please describe.**
(https://nfdi4plants.github.io/AnnotationPrinciples/) does not account for the Protocol usage , acessible by klicking the "info" in SWATE undre protocol

**Describe the solution you'd like**
A clear and concise description of protocol usage.

**Describe alternatives you've considered**
like to have txt protocols of e.g. media or pipeline parameters deposited in the protocol folder of my assay(arc).

**Additional context**

**Comment by Martin-Kuhl** [comment]
I am currently updating the page, more specific on an alternative. 
Will let you know, when it is online..

**Comment by Martin-Kuhl** [comment]
Updated version can be found [here](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/tutorials/AnnotationPatterns.html#annotation-principles-for-swate-building-blocks).
