### ISSUE TITLE
[Bug] Include minimum git version in Tool dependency

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants.knowledgebase#312]
Set minimum requirement for git version in [ARCCommander Setup tutorial](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/ArcCommanderManual/arc_installation_dependencies.html). I would recommend minimum git version 2.32.0.

https://github.com/nfdi4plants/ARCCommander/issues/224

*Not really a bug but still the best fitting of the issue templates IMO*

**Comment by Brilator** [comment]
Plus change from "dependency" to calling it what it is: **Git**. 
We should be more transparent about what's running in the back and allow people to google and learn solving Git-related issues themselves

**Comment by HLWeil** [comment]
You mean "Installing git" instead of "Installing dependencies"? Seems like a good idea.
