### ISSUE TITLE
ontology landscape article

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#324]
- [ ] higher image resolution 
- [ ] list images in [image index](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/main/src/docs/image-index.md)

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/323#issuecomment-1820872012

**Comment by StellaEggels** [comment]
done, I made a pull request
