### ISSUE TITLE
Swate Docs overhaul

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#403]
Swate docs are very much outdated and require a major update to Swate Standalone / ARCitect integration. 

## Level 1
  - [ ] Mention https://swate-alpha.nfdi4plants.org and ARCitect integration
  - [ ] tag or (re)move outdated docs / tutorials as such

## Level 2
- [ ] polish QuickStart, Manual, etc. to remove outdated features
- [ ] replace screenshots of Excel add in

**Comment by Brilator** [comment]
Any volunteers? 😀 
@SabrinaZander @StellaEggels @Freymaurer

**Comment by StellaEggels** [comment]
I can work on it

**Comment by SabrinaZander** [comment]
I can help too. I can replace the screenshots with the ones I took for the workshop slides.
