### ISSUE TITLE
[topic] Youtube titles are not discoverable or searchable

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants.knowledgebase#418]
basically any of our youtube videos, here are some of the worst offenders:
- [I WhatIsAnARCAPracticalApproach](https://www.youtube.com/watch?v=onvuDYCwTZQ)
- [03 04 Update Column contents Update](https://www.youtube.com/watch?v=AwzO3qYB72g)
- [04 AddDetailsAboutYourInvestigation](https://www.youtube.com/watch?v=182Aoqib6og)

These titles seem to be auto-generated from the file names submitted to youtube. I don't think anyone that got shared a video like this will ever find it again via youtube's search. 

I would suggest:
- shorter titles in general
- a short name for the video series after the title of the individual video
- getting rid of any order indicator (e.g. the video numbers), as they are obsolete because we use playlists anyways
- name the playlists exactly as the series name in the video titles

Examples (just suggestions, especially regarding the series names)
- `04 AddDetailsAboutYourInvestigation` -> `Investigation Details - ARCitect RDM manual` 
- `03 04 Update Column contents Update` -> `Update Columns - ARCitect RDM manual`

All videos of a series having this common series title afterwards enables search for the series even if someone forgot the specific video title.

**Comment by ZimmerD** [comment]
The naming of the videos has been improved. I mostly followed your suggestions, but chose a different route regarding the naming of the series. 
Albeit currently only being referenced in the ARCitect and SWATE quickstarts, all videos were designed to document single functionalities to be later on integrated also in the SWATE and ARCitect manuals. Thus the titles were appended by "ARCitect manual" and "SWATE manual". 
I dont think the title of the series referred to in the name should correspond to the playlist titles they are currently integrated in (e.g. ARCitect Quickstart) as in the future one and the same video might be used in different playlists.
