### ISSUE TITLE
[guide] Datamap

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#434]
Swate / ARCitect now allows to "Add Datamap". 
This concept has not been introduced to standard users at all.

I would suggest to

- [ ] add an article about data map
  - [ ] what is it? 
  - [ ] why do we need it? 
  - [ ] how does it relate to other ISA / ARC / CWL concepts and entities
  - [ ] add example table
- [ ] add a guide on creating a data map

I know that it's not all final (see https://github.com/nfdi4plants/ARC-specification/pull/113), but if we offer it to users, we should at least link to a little place holder ("under construction") article.

**Comment by Brilator** [comment]
@Freymaurer ?

**Comment by Freymaurer** [comment]
To be 100% honest with you, i just followed specification, as @HLWeil is on vacation 😅 

It is meant to further describe data files.

**Comment by Brilator** [comment]
Ah great, I missed that in addition to the ARC specification there is another one for ISA-XLSX
https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#datamap-table-sheets

**Comment by HLWeil** [comment]
Maybe use motivation from https://github.com/nfdi4plants/ARC-specification/pull/104?

**Comment by Brilator** [comment]
#474

**Comment by Brilator** [comment]
Currently covered here `/content/docs/start-here/06-datamap.mdx`. 
This is `draft: true` and won't show in build.
