### ISSUE TITLE
Suggestion: place the contribution guide more prominently.

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#44]
Reason is as it is highlighted that the knowledge base is a community effort and this experience should be reflected by the visible option and ease of access to the contribution guide.

could be at the bottom of the sidebar as a "quick link"
could also be at the bottom of the page in a similar way as the "Edit this page" link with the pencil,e.g. with a pencil on the left side of this and with the text "Contribute!"

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/2

**Comment by andreaschrader** [comment]
Right, #2 is related. Thank you for linking these.

#2 should already be matched. When doing my first pull request in the knowledgebase, I landed on the at that time almost empty (it said "Test") CONTRIBUTING.md file. This only happened for the very first pull request. Than I filled the prepared contribution guide in and edited it at some parts. 

Here I mean to link it at the bottom of each page similar to the pencil which is located on the right side ("Edit this page") to have a link to the "Contribution Guide" e.g. on the left side (e.g. with a handshake emoji or also a pencil in front of it?) at the bottom opposing the pencil. Otherwise it would be hidden as a link within the introduction.
The initial idea actually was to place it at the bottom of the sidebar but than there was the suggestion to do it similar as the "Edit this file" link and to place it opposing to it as users most likely(?) scoll down to the bottom of the page to find such information?
