### ISSUE TITLE
[bug] Python virtual environment installation does not need python version number

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants.knowledgebase#467]
Hi,

I just followed the description to install the CWL runner in the WSL on Windows11:
https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/guides/ComputationalWorkflows/cwl_runner_installation.html

Not sure if this is only the case for me but for I did not need to use the version number for the python virtual environment installation:

![image](https://github.com/user-attachments/assets/9f8b387f-e336-48e0-b06a-b73009c077bb)

Maybe someone else could test this.
Thanks!

Best,
Micha

**Comment by Brilator** [comment]
Thanks for the note. 
This is somewhat setup-specific. If your default python is python3, it will work as you suggested. 
Since the first step suggests to install python3, I'd suggest to leave as is; hoping that's less error prone.
