### ISSUE TITLE
[bug] Icon in top left corner not displayed

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants.knowledgebase#492]
I noticed that I can't see the icon in the top left corner of the knowledgebase.
Both in Google Chrome and Microsoft edge.

**Comment by Freymaurer** [comment]
Yes, this is a known bug. We are currently reworking the knowledgebase, which will also solve this issue 😄 Will be quite some changes

**Comment by Freymaurer** [comment]
Should be solved now 🎉
