### ISSUE TITLE
[Topic] ISA File Types

### ISSUE THREAD

**Issue by CMR248** [nfdi4plants/nfdi4plants.knowledgebase#51]
> How to separate multiple entries per row in the investigation file?

**Comment by Brilator** [comment]
I'm wondering where this question / issue came up. Any source?

**Comment by CMR248** [comment]
It was part of a feedback sheet genereated while testing DP tools

**Comment by Brilator** [comment]
Not sure, if I get it right. 
In the isa.investigation.xlsx multiple values are not separated row-wise but column wise (key:value[s]).
And it's recommended not to (manually) adapt the keys (left column), but rather add to it via ARC commander.

**Comment by Brilator** [comment]
In any case, we need better explanations (maybe visualisation) of the different isa file types in the knowledge base.

**Comment by CMR248** [comment]
Exactly! This is the idea of this issue. @Martin-Kuhl is aware of this.
