### ISSUE TITLE
[bug] `Edit this page` link(s) seem to be broken

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants.knowledgebase#518]
### Article URL

https://nfdi4plants.github.io/nfdi4plants.knowledgebase/guides/validate-arc/

### Bug

![image](https://github.com/user-attachments/assets/c3891d92-b04a-4c6c-be54-b3cfd8c79ff5)

**Comment by Brilator** [comment]
Ouch, good catch. True for the whole kb. Probably happened during launch when setting the actual url? @Freymaurer

**Comment by Freymaurer** [comment]
Will look into this tomorrow morning

**Comment by Freymaurer** [comment]
fixed!
