### ISSUE TITLE
Navigating to the actual knowledge always requires to click on getting started

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants.knowledgebase#520]
Is this by design?

**Comment by Freymaurer** [comment]
Yes it is by design. The framework ships with a "hero-banner-esque" landing page. We can change this if more people are annoyed by it

**Comment by Freymaurer** [comment]
We could also link a different page from the nfdi mainpage to skip this landing page

**Comment by Brilator** [comment]
Although I'm also a bit annoyed, I still like the landing page for newcomers. 

> We could also link a different page from the nfdi mainpage to skip this landing page

I like that approach. People coming from the GH repo to the KB or directed their by data stewards still get the simple landing page (including getting started and contributing).
