### ISSUE TITLE
use of icons and mermaid

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#528]
Created a new guide on CWL: https://nfdi4plants.github.io/nfdi4plants.knowledgebase/guides/arc-cwl-wrap-script/

- [ ] I intended to use a simple-icon for commonworkflowlanguage. Possible?
- [ ] adding a mermaid adds a clickable `> Source` at the bottom right corner. Not terrible, but also not needed. 

<img width="898" alt="Screenshot 2024-11-14 at 16 55 27" src="https://github.com/user-attachments/assets/cc170e4b-1d64-4ce7-8030-94ddd16d39a3">

@Freymaurer, can you have a look?

**Comment by Freymaurer** [comment]
What do you mean with simple icon? 

The source button can easily be disabled. Currently it is by design and meint as feature. Super easy to disable if you look at the mermaid component source

**Comment by Brilator** [comment]
> What do you mean with simple icon?

- https://simpleicons.org/
- package-lock.json: "@iconify-json/simple-icons": "^1.2.8",

**Comment by Freymaurer** [comment]
And you meant to use that inside of the mermaid graph?

**Comment by Freymaurer** [comment]
Sadly starlight does currently not support adding custom icons to the starlight components. But they are currently working on it:

https://github.com/withastro/starlight/discussions/967#discussioncomment-11201702

**Comment by Brilator** [comment]
Ah alright. I thought we're using them for the author component already.

**Comment by Freymaurer** [comment]
in all custom components designed by us we can use any icon we want, but if i understood you correctly you want a custom icon in a `<Tab>`

**Comment by Freymaurer** [comment]
Will close for now then
