### ISSUE TITLE
Correct Quickstart repo README

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#63]
The QuickStart repo README.md needs to be corrected with respect to the respective links as these are dead. As it is archive I can not push a new branch and place a pull request.
This is what could be used to correct for this:
Please refer to the [DataPLANT website](https://nfdi4plants.org/nfdi4plants.knowledgebase/index.html) or the corresponding new location of the [QuickStart](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/QuickStart_arcCommander.html) for the latest versions of the  ARC Commander QuickStart.

**Comment by Brilator** [comment]
I'd rather suggest to delete the old repo now, as it has been archived for over half a year or at least make it private. 
Plus: if we update it now, GitHub pushes it to the top again suggesting that it is still up to date / relevant.
Any pointer (link) to the repo needs to be removed / adapted; any person still checking this repo should see (archived) or be told, that it is deprecated and replaced elsewhere.

**Comment by Martin-Kuhl** [comment]
@Brilator I think you are the only person with administration rights to the repo. I am not aware of any pointers to the repo, so from my point of view you can delete it.

**Comment by Brilator** [comment]
Double-check the knowledge base for possible link to archived

**Comment by andreaschrader** [comment]
Closing this old repo solved this issues. Links were only not matching anymore in the old repo's README.md. Therfore, I am closing this issue now.
