### ISSUE TITLE
Add ArcCommander credential manager storing setup

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants.knowledgebase#64]
In the section [sharing your arc](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/QuickStart_arcCommander.html#sharing-your-arc), prior to running the remote token get command, it might be necessary to setup git credential storing:

Windows:
git config --global credential.helper cache
or
git config --global credential.helper store

Mac:
git config --global credential.helper osxkeychain

-------
 
Moved from https://github.com/nfdi4plants/arcCommander-docs/issues/4

**Comment by Brilator** [comment]
I'd suggest to also add this here https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/implementation/ArcCommanderManual/arc_access.html

**Comment by HLWeil** [comment]
Agreed!

**Comment by Brilator** [comment]
What's the command for Linux?

**Comment by Brilator** [comment]
`git config --global credential.helper store` seemed to do the job on ubuntu

**Comment by Brilator** [comment]
https://github.com/nfdi4plants/nfdi4plants.knowledgebase/pull/66/commits/f8a5b9881126b076cdfbddb27803b3141dba8498

**Comment by Martin-Kuhl** [comment]
#68
