### ISSUE TITLE
Typo in Arc Quickstart?

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/nfdi4plants.knowledgebase#8]
I think I found a typo in the instructions. In section "ARC synchronization", 3., it reads:

"In case you want to create a new remote repository at this URL, it needs to be assembled as the following example:"

`# https://git.nfdi4plants.org/<yourusername>/<yourarc></yourarc></yourusername>`

I think it should be:

`# https://git.nfdi4plants.org/<yourusername>/<yourarc>`

**Comment by Brilator** [comment]
And wait again... I don't get it. 
This seems correct in the [markdown](https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/main/src/docs/tutorials/QuickStart_arc.md#arc-synchronization), but renders incorrectly [online](https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/tutorials/QuickStart_arc.html#arc-synchronization).
