### ISSUE TITLE
auto-update "last updated at"

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#80]
I'd actually prefer to have the "last-updated at" on top to update automatically based on git commit. 
We've decided against this at some point, since even the smallest typo would fake-suggest a revision. 

But a) I keep forgetting to change the date and b) even a small change shows the kb lives.

**Comment by Brilator** [comment]
If decided positively, would need to transfer the issue to web-components @Freymaurer

**Comment by Freymaurer** [comment]
This is not trivial to implement and very low priority for me. The correct place for this issue is [Nfdi4Plants.Fornax](https://github.com/Freymaurer/Nfdi4Plants.Fornax). If you want to give it a shot i am more than happy.

**Comment by Brilator** [comment]
Gave it a shot with python, but I can't stop `frontmatter` from formatting ISO date to string... 

https://github.com/nfdi4plants/nfdi4plants.knowledgebase/blob/autoup-date-test/up-date.ipynb

And not sure about the dependencies.
