### ISSUE TITLE
Name article contributors

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants.knowledgebase#81]
Some comparable (e.g. NFDI4xyz) knowledge bases list the individual contributors / authors at the bottom of the site. 
I'd suggest to add this here (e.g. author + ORCID) as well as it might make contributing more attractive. 

Not sure wether this is a speaker-level decision or wether this has actually been decided (against) at some point. 
@CMR248 @muehlhaus

**Comment by Brilator** [comment]
Somewhat related: cc-by license #79

**Comment by Brilator** [comment]
Yes, some of the concepts are commonplace. Not so, if we want to make it a place for white-papering visions, etc.

**Comment by andreaschrader** [comment]
[enhancement]

Apart of the article-related discussion above we could thank contributors at the end of the landing page by classify contributor to  

- __founding or initiating contributors__  
- __major contributors__ (participants in Knowledgbase development at Hackathons plus more than 10 commits or more than 30 commits)
- __other contributors__. 

The names can be listed respectively and add a sentence that we ask contributors themselves who become e.g. major contributors over time to request this change themselves via pull request which are in any case reviewd by one of us.
