### ISSUE TITLE
Manual for DataPLAN?

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants.knowledgebase#88]

**Comment by andreaschrader** [comment]
- Idea: Harmonize Knowledgebase content.  
- Derived from a response to #20: https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/20#issuecomment-1360058411  
- Create Quickstart, Manual and maybe also developers docs for the tools with high user exposure

**Comment by Brilator** [comment]
Would close this for now as DataPLAN ships with its own tutorial and help (manual). 
Feel free to reopen, if you think this should be part incorporated in the knowledge base.
@xiaoranzhou
